"""Make library_id in Book not-nullable.

Revision ID: 1590ade03c8e
Revises: 3b1a7d9368a3
Create Date: 2024-10-03 20:52:29.572556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1590ade03c8e'
down_revision: Union[str, None] = '3b1a7d9368a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
