"""Update book author column length

Revision ID: 333dc7cd7ffc
Revises: 536c70d5726b
Create Date: 2024-10-03 15:58:25.760006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '333dc7cd7ffc'
down_revision: Union[str, None] = '536c70d5726b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'author',
               existing_type=sa.VARCHAR(),
               type_=sa.CHAR(length=50),
               existing_nullable=False)
    op.alter_column('book', 'title',
               existing_type=sa.VARCHAR(),
               type_=sa.CHAR(length=80),
               existing_nullable=False)
    op.alter_column('book', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.CHAR(length=8),
               existing_nullable=False)
    op.alter_column('library', 'name',
               existing_type=sa.VARCHAR(),
               type_=sa.CHAR(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('library', 'name',
               existing_type=sa.CHAR(length=30),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('book', 'status',
               existing_type=sa.CHAR(length=8),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('book', 'title',
               existing_type=sa.CHAR(length=80),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('book', 'author',
               existing_type=sa.CHAR(length=50),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
