"""Remove publication date from Book.

Revision ID: 5eada7c8edfb
Revises: 333dc7cd7ffc
Create Date: 2024-10-03 20:13:31.944393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5eada7c8edfb'
down_revision: Union[str, None] = '333dc7cd7ffc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'publication_year')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('publication_year', sa.DATE(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
