"""Make library_id in Book not-nullable.

Revision ID: 7ac053b21a04
Revises: 1590ade03c8e
Create Date: 2024-10-03 20:52:50.944185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ac053b21a04'
down_revision: Union[str, None] = '1590ade03c8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'library_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'library_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
